### ISSUE TITLE
Missing translation string

### ISSUE THREAD

**Issue by m0rff** [codekanzlei/cake-cktools#19]
See: https://github.com/scherersoftware/cake-cktools/search?q=utility.toggle_content&unscoped_q=utility.toggle_content

I have no idea how to fix this since there is no I18N command configured.

**Comment by felixkempf** [comment]
What do you mean, there is no command configured? 

Just install the composer dependencies and execute the I18nShell from cakephp

**Comment by m0rff** [comment]
Fixed by #22
